import createClient from "openapi-fetch";
import type { paths } from "./community-archive"; // generated by openapi-typescript

export const communityArchiveClient = createClient<paths>({
    baseUrl: "https://fabxmporizzqflnftavs.supabase.co/rest/v1",
    headers: { apikey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhYnhtcG9yaXp6cWZsbmZ0YXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjIyNDQ5MTIsImV4cCI6MjAzNzgyMDkxMn0.UIEJiUNkLsW28tBHmG-RQDW-I5JNlJLt62CSk9D_qG8" }
});