import createClient from "openapi-fetch";
import type { paths } from "./community-archive"; // generated by openapi-typescript

export const communityArchiveClient = createClient<paths>({
    baseUrl: process.env.COMMUNITY_ARCHIVE_API_URL,
    headers: { apikey: process.env.COMMUNITY_ARCHIVE_API_TOKEN }
});