// table schema generated by introspection
import { vector32 } from "@/db/types/vector";
import {
    integer,
    sqliteTable,
    text,
} from "drizzle-orm/sqlite-core";



export const docsTable = sqliteTable(
    "docs",
    {
        id: text().primaryKey().notNull(),
        source: text({ enum: ["community-archive"] }).notNull(),
        content: text().notNull(),
        createdAt: integer().notNull(),
        creatorId: text().notNull(),
        embedding: vector32(),
    }
);